openapi: 3.0.3
info:
  title: Stat service
  version: 1.0.0
  contact: {}
servers:
  - url: http://localhost:4000
paths:
  /api/stats/countActiveUsers:
    post:
      summary: Count active users
      description: Count active users
      operationId: countActiveUsers
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
                  example: '123'
            examples:
              Count active users:
                value:
                  userId: '123'
      responses:
        '200':
          description: ''
tags: []
